- label: "Hello"
  message: "World"
  color: "green"

- message: "Go yellow"
  color: "yellow"

- message: "$payload.pull_request.user.login"
  color: "green"

- label: "JIRA"
  message: "$issuePrefix"
  color: "#0052CC"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"
