- label: "Hello"
  message: "World"
  color: "green"

- message: "Go yellow"
  color: "pink"

- label: "PR Creator"
  message: "$payload.pull_request.user.login"
  color: "purple"

- label: "JIRA"
  message: "$issuePrefix"
  color: "#0052CC"
  url: "https://jira.company.com/browse/$issuePrefix"
  when: "$issuePrefix"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 200"

- message: "Feature"
  when: "$labels.includes('Feature')"
