# https://pullrequestbadge.com/

# PR STATS

- label: "Commits"
  message: "$commits"
  color: "#9CFFBA"

- label: "Files"
  message: "$changedFiles"
  color: "#FFF09C"

- label: "PR #"
  message: "$prNumber"
  color: "#D89CFF"

# LABEL

- message: "Feature"
  when: "$labels.includes('feature')"
  color: "#9CCAFF"

- message: "Documentation"
  when: "$labels.includes('documentation')"
  color: "#FF9CC1"

# SIZE

- label: "PR Size"
  message: "Large"
  color: "#FF9C9C"
  when: "$additions > 200"

- label: "PR Size"
  message: "Small"
  color: "#11D301"
  when: "$additions < 50"
