# https://pullrequestbadge.com/

# PR STATS

- label: "Commits"
  message: "$commits"
  color: "#958500"

- label: "Files"
  message: "$changedFiles"
  color: "#00958C"

- label: "PR #"
  message: "$prNumber"
  color: "#630095"

- label: "Additions"
  message: "$additions"
  color: "#51AB00"

- label: "Deletions"
  message: "$deletions"
  color: "#AB0000"

# LABEL

- message: "Feature"
  when: "$labels.includes('feature')"
  color: "#95005C"

- message: "Documentation"
  when: "$labels.includes('documentation')"
  color: "#8E0095"

# SIZE

- label: "PR Size"
  message: "Small"
  color: "#950000"
  when: "$additions <= 50"

- label: "PR Size"
  message: "Medium"
  color: "#950000"
  when: "$additions > 50 && $additions < 200"

- label: "PR Size"
  message: "Large"
  color: "#950000"
  when: "$additions >= 200"
