# https://pullrequestbadge.com/

- label: "Commits"
  message: "$commits"
  color: "magenta"

- label: "Altered"
  message: "$changedFiles files"
  color: "black"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 200"

- label: "PR"
  message: "#$prNumber"
  color: "silver"

- label: "PR Size"
  message: "Small"
  color: "red"
  when: "$additions < 50"

- message: "Feature"
  when: "$labels.includes('feature')"

- message: "Documentation"
  when: "$labels.includes('documentation')"
