name: Hello actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

# global variable can be rferenced by all jobs
env:
  name: Alexis
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: Ray # local variable overrides global variable
    steps:
      - name: Run a one-line script
        run: |
          echo Hello $name!
          echo Actor: ${{ github.actor }}
          echo Committed By: ${{ github.events.commits[0].author }}

  weather:
    runs-on: ubuntu-latest
    env:
      location: "28.550, -81.40"
      lang: en
      units: us
      exclude: "minutely,hourly,daily,alerts,flags"
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: Current Weather
        run: curl -s --url https://api.darksky.net/forecast/$dark_sky_secret/$location?lang=$lang&units=$units&exclude=$exclude

  pull-request-only:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' #conditional using the github object, which contains info of the repo
    needs: build # dependency, such that will only run when the job it needs is done
    steps:
      - name: Run a multi-line script
        run: |
          echo Add another actions to build,
          echo hello global var: $namet.

  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "SGITHUB_CONTEXT"
# CONTEXT: https://docs.github.com/en/actions/learn-github-actions/contexts
# EXPRESSIONS:
# added new lines
