name: Hello actions

on: 
  push: 
    branches:
      - main
  pull_request:
    types: [closed]


jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello World!
    - name: Run a multi-line script
      run: |
        echo Add another actions to build,
        echo test, and deploy your project.
