name: Example
uses: lowlighter/metrics@latest
with:
  template: repository
  filename: metrics.repository.svg
  token: ${{ secrets.metrics_token }}
  user: adamsimonini
  repo: github-possibilities
  plugin_lines: yes
  plugin_followup: yes
  plugin_projects: yes
  plugin_projects_repositories: lowlighter/metrics/projects/1
